# EXPERIMENT 2: Numerical Python 

### Normalization Problem:

In [1]:
#Create a random 5 x 5 ndarray and store it in variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

import numpy as np
def main():
    X = np.random.random((5,5))
    mean = X.mean()
    std = X.std()

    print("Your randomized array is as follows: ")
    print(str(X) + "\n")

    print("Your mean is: " + str(mean) + ", while your standard deviation is: " + str(std) + "." + "\n")
    print("The normalized array is as follows: ")

    X_normalized = ((X-mean)/std)

    print(X_normalized)

    np.save('X_normalized.npy', X_normalized)

    print("\nYour normalized array has been saved as 'X_normalized.npy', you may find it in your local disk.")

main()

Your randomized array is as follows: 
[[0.34625599 0.53258442 0.40008595 0.2522471  0.97695886]
 [0.08949623 0.04628099 0.32207255 0.2592403  0.29501305]
 [0.55545339 0.40842219 0.71952345 0.92529775 0.32351042]
 [0.740912   0.12931278 0.89041697 0.3636591  0.29847436]
 [0.5218929  0.12136994 0.49916661 0.56265501 0.42395796]]

Your mean is: 0.44017041078507857, while your standard deviation is: 0.250789390165924.

The normalized array is as follows: 
[[-0.37447525  0.3684925  -0.15983314 -0.74932721  2.14039538]
 [-1.39828155 -1.57059842 -0.47090455 -0.72144243 -0.57880186]
 [ 0.45968046 -0.12659317  1.11389496  1.93440136 -0.46517114]
 [ 1.19917986 -1.23951669  1.79531741 -0.30508192 -0.56500019]
 [ 0.32586105 -1.27118803  0.235242    0.48839626 -0.06464569]]

Your normalized array has been saved as 'X_normalized.npy', you may find it in your local disk.


### Normalization Problem Data:

In [2]:
XNdata = np.load('X_normalized.npy')
XNdata

array([[-0.37447525,  0.3684925 , -0.15983314, -0.74932721,  2.14039538],
       [-1.39828155, -1.57059842, -0.47090455, -0.72144243, -0.57880186],
       [ 0.45968046, -0.12659317,  1.11389496,  1.93440136, -0.46517114],
       [ 1.19917986, -1.23951669,  1.79531741, -0.30508192, -0.56500019],
       [ 0.32586105, -1.27118803,  0.235242  ,  0.48839626, -0.06464569]])

### Divisible by 3 Problem:

In [3]:
#Create a 10x10 ndarray from the squares of the first 100 integers. 
#From this ndarray, determine all the elements that are divisible by 3. Save the result as div_by_3.npy

import numpy as np
def main():
    Y = np.arange(1, 101)
    Y_squared = (Y**2).reshape(10, 10)

    is_divisible_by_3 = Y_squared % 3 == 0

    div_by_3 = (Y_squared[is_divisible_by_3]).reshape(3,11)

    print("Your initial 10x10 array of the squares of the first 100 integers is as follows: ")
    print(str(Y_squared) + "\n")

    print("The integers divisible by 3 in the 10x10 array is as follows: ")
    print(div_by_3)

    np.save('div_by_3.npy', div_by_3)

    print("\nThe array of numbers divisible by 3 has been saved as 'div_by_3.npy', you may find it in your local disk.")
    
main()

Your initial 10x10 array of the squares of the first 100 integers is as follows: 
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

The integers divisible by 3 in the 10x10 array is as follows: 
[[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]

The array of numbers divisible by 3 has been sa

### Divisible by 3 Problem Data:

In [4]:
DB3data = np.load('div_by_3.npy')
DB3data

array([[   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089],
       [1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356],
       [4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801]])