In [6]:
import numpy as np #Imports the NumPy Library
def main():
    X = np.random.random((5,5)) #Generates a 5x5 array with randomized values
    print("Your randomized array is as follows:\n", X) #Outputs the generated randomized array
    mean = X.mean() #Finds the mean value of array X
    std = X.std() #Finds the standard deviation of array X
    print("\nYour mean is: " + str(mean) + ", while your standard deviation is: " + str(std) + "." + "\n") #Outputs the mean and standard deviation

    X_normalized = ((X-mean)/std) #Solves for the normalized values of the array
    print("The normalized array is as follows:\n", X_normalized) #Outputs the normalized values for the array

    np.save('X_normalized.npy', X_normalized) #Saves the normalized values as X_normalized.npy

    print("\nYour normalized array has been saved as 'X_normalized.npy', you may find it in your local disk.") #Outputs a message notifying the user of the saved file

main()

Your randomized array is as follows:
 [[0.15206009 0.66369802 0.86533987 0.45766037 0.59830395]
 [0.15450721 0.6472665  0.15987633 0.68321271 0.91216595]
 [0.04483608 0.23178494 0.22544633 0.79454958 0.81696265]
 [0.74500067 0.59008715 0.24927572 0.35723216 0.08680182]
 [0.19409815 0.90907851 0.29648924 0.53543562 0.56279653]]

Your mean is: 0.47735864613575435, while your standard deviation is: 0.27651628652100035.

The normalized array is as follows:
 [[-1.17641734  0.6738821   1.40310442 -0.07123731  0.43738943]
 [-1.16756751  0.61445877 -1.14815051  0.74445547  1.57244736]
 [-1.56418476 -0.88809854 -0.91102163  1.14709673  1.2281519 ]
 [ 0.96790692  0.40767401 -0.82484445 -0.43442823 -1.4124189 ]
 [-1.02438992  1.56128188 -0.65410039  0.21003092  0.30897958]]

Your normalized array has been saved as 'X_normalized.npy', you may find it in your local disk.


In [5]:
import numpy as np #Imports the NumPy Library
def main():
    Y = np.arange(1, 101) #Generates an array with the values of 1 to 100
    Y_squared = (Y**2).reshape(10, 10) #Squares all the values in the array and reshapes the array to a 10x10 shape

    is_divisible_by_3 = Y_squared % 3 == 0 #Stores a condition for values that are divisible by 3 
    div_by_3 = (Y_squared[is_divisible_by_3]).reshape(3,11) #Finds all values according to the condition and reshapes the array to 3x11

    print("Your initial 10x10 array of the squares of the first 100 integers is as follows:\n", Y_squared) #Outputs the squared values of the initial array
    print("\nThe integers divisible by 3 in the 10x10 array is as follows:\n", div_by_3) #Outputs the array with values divisible by 3

    np.save('div_by_3.npy', div_by_3) #Saves the div_by_3 array as 'div_by_3.npy' in the user's local directory

    print("\nThe array of numbers divisible by three has been saved as 'div_by_3.npy', you may find it in your local disk.") #Outputs a message notifying the user of the saved file
    
main()

Your initial 10x10 array of the squares of the first 100 integers is as follows:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

The integers divisible by 3 in the 10x10 array is as follows:
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]

The array of numbers divisible by three has bee